#==============================================================================
#   WARNING!!  This file is overwritten by the Block UI Styler while generating
#   the automation code. Any modifications to this file will be lost after
#   generating the code again.
# 
#        Filename:  D:\Dosyalarım Ahmed\Code\NX_Open\Deep_Test\Deep_test.py
# 
#         This file was generated by the NX Block UI Styler
#         Created by: topcu
#               Version: NX 12
#               Date: 02-01-2025  (Format: mm-dd-yyyy)
#               Time: 23:22 (Format: hh-mm)
# 
#==============================================================================

#==============================================================================
#   Purpose:  This TEMPLATE file contains Python source to guide you in the
#   construction of your Block application dialog. The generation of your
#   dialog file (.dlx extension) is the first step towards dialog construction
#   within NX.  You must now create a NX Open application that
#   utilizes this file (.dlx).
# 
#   The information in this file provides you with the following:
# 
#   1.  Help on how to load and display your Block UI Styler dialog in NX
#       using APIs provided in NXOpen.BlockStyler namespace
#   2.  The empty callback methods (stubs) associated with your dialog items
#       have also been placed in this file. These empty methods have been
#       created simply to start you along with your coding requirements.
#       The method name, argument list and possible return values have already
#       been provided for you.
#==============================================================================

#------------------------------------------------------------------------------
# These imports are needed for the following template code
#------------------------------------------------------------------------------
import NXOpen
import NXOpen.BlockStyler

#------------------------------------------------------------------------------
# Represents Block Styler application cls
#------------------------------------------------------------------------------
class Deep_test:
    # static class members
    theSession = None
    theUI = None
    
    #------------------------------------------------------------------------------
    # Constructor for NX Styler class
    #------------------------------------------------------------------------------
    def __init__(self):
        try:
            self.theSession = NXOpen.Session.GetSession()
            self.theUI = NXOpen.UI.GetUI()
            self.theDlxFileName = r"D:\Dosyalarım Ahmed\Code\NX_Open\Deep_Test\Deep_test.dlx"
            self.theDialog = self.theUI.CreateDialog(self.theDlxFileName)
            self.theDialog.AddApplyHandler(self.apply_cb)
            self.theDialog.AddOkHandler(self.ok_cb)
            self.theDialog.AddUpdateHandler(self.update_cb)
            self.theDialog.AddInitializeHandler(self.initialize_cb)
            self.theDialog.AddDialogShownHandler(self.dialogShown_cb)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            raise ex
        
    
    # ------------------------------- DIALOG LAUNCHING ---------------------------------
    # 
    #     Before invoking this application one needs to open any part/empty part in NX
    #     because of the behavior of the blocks.
    # 
    #     Make sure the dlx file is in one of the following locations:
    #         1.) From where NX session is launched
    #         2.) $UGII_USER_DIR/application
    #         3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    #             recommended. This variable is set to a full directory path to a file 
    #             containing a list of root directories for all custom applications.
    #             e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    # 
    #     You can create the dialog using one of the following way:
    # 
    #     1. Journal Replay
    # 
    #         1) Replay this file through Tool->Journal->Play Menu.
    # 
    #     2. USER EXIT
    # 
    #         1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    #         2) Invoke the Shared Library through File->Execute->NX Open menu.
    # 
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # This method shows the dialog on the screen
    #------------------------------------------------------------------------------
    def Show(self):
        try:
            self.theDialog.Show()
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Method Name: Dispose
    #------------------------------------------------------------------------------
    def Dispose(self):
        if self.theDialog != None:
            self.theDialog.Dispose()
            self.theDialog = None
    
    #------------------------------------------------------------------------------
    # ---------------------Block UI Styler Callback Functions--------------------------
    #------------------------------------------------------------------------------
    
    #------------------------------------------------------------------------------
    # Callback Name: initialize_cb
    #------------------------------------------------------------------------------
    def initialize_cb(self):
        try:
            self.PointSelection = self.theDialog.TopBlock.FindBlock("PointSelection")
            self.coord_system0 = self.theDialog.TopBlock.FindBlock("coord_system0")
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: dialogShown_cb
    # This callback is executed just before the dialog launch. Thus any value set 
    # here will take precedence and dialog will be launched showing that value. 
    #------------------------------------------------------------------------------
    def dialogShown_cb(self):
        try:
            # ---- Enter your callback code here -----
            pass
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
    
    #------------------------------------------------------------------------------
    # Callback Name: apply_cb
    #------------------------------------------------------------------------------
    def apply_cb(self):
        errorCode = 0
        try:
            # Seçilen noktaları ve koordinat sistemini al
            selected_points = self.PointSelection.GetSelectedObjects()
            selected_coord_system = self.coord_system0.GetSelectedObjects()

            if selected_points and selected_coord_system:
                # Koordinat sistemini al
                coord_system = selected_coord_system[0]
                origin = coord_system.Origin
                orientation = coord_system.Orientation

                # Noktaların koordinatlarını koordinat sistemine göre dönüştür
                self.print_transformed_points_table(selected_points, origin, orientation)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            errorCode = 1
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return errorCode
    
    #------------------------------------------------------------------------------
    # Callback Name: update_cb
    #------------------------------------------------------------------------------
    def update_cb(self, block):
        try:
            if block == self.PointSelection or block == self.coord_system0:
                # ---- Enter your code here -----
                pass
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return 0
    
    #------------------------------------------------------------------------------
    # Callback Name: ok_cb
    #------------------------------------------------------------------------------
    def ok_cb(self):
        errorCode = 0
        try:
            # Apply işlemini çağır
            errorCode = self.apply_cb()
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            errorCode = 1
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return errorCode
    
    #------------------------------------------------------------------------------
    # Function Name: print_transformed_points_table
    # Seçilen noktaların koordinatlarını koordinat sistemine göre dönüştürür ve tablo halinde gösterir
    #------------------------------------------------------------------------------
    def print_transformed_points_table(self, selected_points, origin, orientation):
        try:
            listing_window = self.theSession.ListingWindow
            listing_window.Open()
            listing_window.WriteLine("Seçilen Noktaların Koordinat Sistemi Göre Koordinatları (Sıralı):")
            
            # Tablo başlığını yazdır
            listing_window.WriteLine("{:<5} {:<10} {:<10} {:<10}".format("No", "X", "Y", "Z"))
            listing_window.WriteLine("-" * 40)

            # Seçilen noktaları sıralı olarak yazdır
            for index, point in enumerate(selected_points, start=1):
                # Noktanın koordinatlarını dönüştür
                original_coords = point.Coordinates
                transformed_coords = self.transform_point(original_coords, origin, orientation)

                listing_window.WriteLine("{:<5} {:<10.3f} {:<10.3f} {:<10.3f}".format(
                    index, transformed_coords.X, transformed_coords.Y, transformed_coords.Z
                ))
        except Exception as ex:
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    
    #------------------------------------------------------------------------------
    # Function Name: transform_point
    # Noktayı koordinat sistemine göre dönüştürür
    #------------------------------------------------------------------------------
    def transform_point(self, point, origin, orientation):
        # Noktayı koordinat sistemine göre dönüştür
        translated_point = NXOpen.Point3d(
            point.X - origin.X,
            point.Y - origin.Y,
            point.Z - origin.Z
        )

        # Dönüşüm matrisini uygula
        transformed_point = NXOpen.Point3d(
            orientation.Element.Xx * translated_point.X + orientation.Element.Xy * translated_point.Y + orientation.Element.Xz * translated_point.Z,
            orientation.Element.Yx * translated_point.X + orientation.Element.Yy * translated_point.Y + orientation.Element.Yz * translated_point.Z,
            orientation.Element.Zx * translated_point.X + orientation.Element.Zy * translated_point.Y + orientation.Element.Zz * translated_point.Z
        )

        return transformed_point
    
    #------------------------------------------------------------------------------
    # Function Name: GetBlockProperties
    # Returns the propertylist of the specified BlockID
    #------------------------------------------------------------------------------
    def GetBlockProperties(self, blockID):
        try:
            return self.theDialog.GetBlockProperties(blockID)
        except Exception as ex:
            # ---- Enter your exception handling code here -----
            self.theUI.NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
        
        return None
    
def main():
    theDeep_test = None
    try:
        theDeep_test =  Deep_test()
        #  The following method shows the dialog immediately
        theDeep_test.Show()
    except Exception as ex:
        # ---- Enter your exception handling code here -----
        NXOpen.UI.GetUI().NXMessageBox.Show("Block Styler", NXOpen.NXMessageBox.DialogType.Error, str(ex))
    finally:
        if theDeep_test != None:
            theDeep_test.Dispose()
            theDeep_test = None
    
if __name__ == '__main__':
    main()